version: "3"

services:
  ruuvilogger:
    build: .
    container_name: lepinkainen/ruuvilogger
    privileged: true
    restart: always
    network_mode: host
    extra_hosts:
      - "mqtt-server:192.168.1.12"
