version: "3"

services:
  ruuvilogger:
    image: lepinkainen/ruuvilogger
    container_name: ruuvilogger
    env_file: .env
    privileged: true
    restart: always
    network_mode: host
    extra_hosts:
      - "mqtt-server:192.168.1.12"
